dist: bionic
language: node_js
node_js:
  - "8.9.3"
  - "10"
  - "12"
before_install:
  - sudo apt-get install -y nginx
  - npm install -g codecov
install:
  - which nginx
script:
  - make codecov
after_script:
  - codecov