dist: bionic
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
before_install:
  - sudo apt-get install -y nginx
  - npm install codecov
install:
  - which nginx
script:
  - make codecov
after_script:
  - ./node_modules/.bin/codecov